#!/usr/bin/env bash

set -euo pipefail

WSL_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$WSL_SCRIPTS_DIR/.." && pwd)"
REQUIRED_COMPILE_SDK="35"
REQUIRED_BUILD_TOOLS_VERSION="36.0.0"
GRADLE_PROXY_OVERRIDE_NAME="anisubroid-wsl-proxy.gradle"

# Host-side locations mounted via drvfs. Adjust if your drives differ.
WINDOWS_SDK_ROOT="${WINDOWS_SDK_ROOT:-/mnt/e/Android/Sdk}"
WINDOWS_GRADLE_USER_HOME="${WINDOWS_GRADLE_USER_HOME:-/mnt/e/Gradle/user-home}"

# The Windows SDK's platforms/ and licenses/ directories are pure data and are
# reused as-is. build-tools/ and platform-tools/ contain Windows binaries; the
# Gradle build pulls aapt2 from Maven, and adb.exe works via WSL interop, so a
# shared SDK needs no Linux binaries at all. Set ANDROID_SDK_ROOT to override.
default_sdk_root() {
    if [[ -n "${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}" ]]; then
        printf '%s\n' "${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
    elif [[ -d "$WINDOWS_SDK_ROOT/platforms" ]]; then
        printf '%s\n' "$WINDOWS_SDK_ROOT"
    else
        printf '%s\n' "$HOME/Android/Sdk"
    fi
}

ANDROID_SDK_ROOT="$(default_sdk_root)"
ANDROID_HOME="$ANDROID_SDK_ROOT"

GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

export ANDROID_SDK_ROOT
export ANDROID_HOME
export GRADLE_USER_HOME

is_shared_sdk_root() {
    [[ "$ANDROID_SDK_ROOT" == /mnt/* ]]
}

# One-time copy of the host's Gradle dependency cache (jars + module metadata)
# and wrapper dists into the WSL-local GRADLE_USER_HOME. Generated caches are
# path-keyed per OS and must NOT be shared; a snapshot copy avoids lock
# contention and stays valid even as the two caches later diverge.
seed_gradle_home() {
    if [[ "$GRADLE_USER_HOME" == /mnt/* ]]; then
        return 0
    fi
    if [[ ! -d "$WINDOWS_GRADLE_USER_HOME/caches/modules-2" ]]; then
        return 0
    fi
    if [[ -d "$GRADLE_USER_HOME/caches/modules-2" ]]; then
        return 0
    fi

    printf 'Seeding Gradle cache from %s ...\n' "$WINDOWS_GRADLE_USER_HOME"
    mkdir -p "$GRADLE_USER_HOME/caches"
    cp -r "$WINDOWS_GRADLE_USER_HOME/caches/modules-2" "$GRADLE_USER_HOME/caches/"
    if [[ -d "$WINDOWS_GRADLE_USER_HOME/wrapper/dists" ]]; then
        mkdir -p "$GRADLE_USER_HOME/wrapper"
        cp -r "$WINDOWS_GRADLE_USER_HOME/wrapper/dists" "$GRADLE_USER_HOME/wrapper/"
    fi
    printf 'GRADLE_USER_HOME=%s\n' "$GRADLE_USER_HOME"
}

# WSL2 NAT mode: the Windows host is reachable at the default gateway, not at
# 127.0.0.1. In mirrored networking mode 127.0.0.1 also reaches the host.
wsl_host_ip() {
    ip route 2>/dev/null | awk '/^default/ { print $3; exit }'
}

tcp_open() {
    nc -z -w2 "$1" "$2" >/dev/null 2>&1
}

# A TCP port can appear open while the proxy still refuses WSL traffic, so
# verify with a real request through the proxy instead of nc alone.
http_proxy_works() {
    local proxy_url="$1"
    local code
    code="$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 4 \
        --proxy "$proxy_url" https://dl.google.com 2>/dev/null || true)"
    [[ -n "$code" && "$code" != "000" ]]
}

gradle_properties_proxy() {
    local gradle_properties="$PROJECT_ROOT/gradle.properties"
    PROJECT_PROXY_HOST=""
    PROJECT_PROXY_PORT=""
    if [[ -f "$gradle_properties" ]]; then
        PROJECT_PROXY_HOST="$(grep -oE '^systemProp\.https\.proxyHost=.*' "$gradle_properties" | head -n 1 | cut -d= -f2- | tr -d '[:space:]')"
        PROJECT_PROXY_PORT="$(grep -oE '^systemProp\.https\.proxyPort=.*' "$gradle_properties" | head -n 1 | cut -d= -f2- | tr -d '[:space:]')"
    fi
}

# gradle.properties pins a proxy (127.0.0.1:7897) that is unreachable from WSL
# in NAT mode. Since systemProp.* cannot be overridden by command-line flags,
# generate a Gradle init script that fixes the system properties after
# gradle.properties has been applied. Scoped to Linux builds of this project
# so it is inert when GRADLE_USER_HOME is shared with Windows.
ensure_gradle_proxy_override() {
    gradle_properties_proxy
    local override_dir="$GRADLE_USER_HOME/init.d"
    local override_file="$override_dir/$GRADLE_PROXY_OVERRIDE_NAME"

    if [[ -z "$PROJECT_PROXY_HOST" ]]; then
        rm -f "$override_file"
        return 0
    fi

    if tcp_open "$PROJECT_PROXY_HOST" "${PROJECT_PROXY_PORT:-7897}"; then
        # Mirrored networking (or a listener inside WSL): the pinned proxy works.
        rm -f "$override_file"
        return 0
    fi

    mkdir -p "$override_dir"
    local effective_host="" effective_port=""
    if [[ -n "${WSL_PROXY_URL:-}" ]]; then
        effective_host="${WSL_PROXY_URL#*://}"
        effective_port="${effective_host##*:}"
        effective_host="${effective_host%%:*}"
    fi

    {
        printf '// Generated by wsl-scripts/common.sh; do not edit.\n'
        printf '// gradle.properties pins an unreachable proxy from WSL; adjust it here.\n'
        printf 'def wslProjectRoot = %s\n' "'$PROJECT_ROOT'"
        printf 'def onLinux = System.getProperty(%s)?.toLowerCase()?.contains(%s)\n' "'os.name'" "'linux'"
        printf 'def buildDir = gradle.startParameter.currentDir?.canonicalPath ?: \"\"\n'
        printf 'if (onLinux && buildDir.startsWith(wslProjectRoot)) {\n'
        if [[ -n "$effective_host" ]]; then
            printf '    System.setProperty(%s, %s)\n' "'http.proxyHost'" "'$effective_host'"
            printf '    System.setProperty(%s, %s)\n' "'http.proxyPort'" "'$effective_port'"
            printf '    System.setProperty(%s, %s)\n' "'https.proxyHost'" "'$effective_host'"
            printf '    System.setProperty(%s, %s)\n' "'https.proxyPort'" "'$effective_port'"
        else
            printf '    System.clearProperty(%s)\n' "'http.proxyHost'"
            printf '    System.clearProperty(%s)\n' "'http.proxyPort'"
            printf '    System.clearProperty(%s)\n' "'https.proxyHost'"
            printf '    System.clearProperty(%s)\n' "'https.proxyPort'"
        fi
        printf '}\n'
    } > "$override_file"

    printf 'GRADLE_PROXY_OVERRIDE=%s\n' "$override_file"
}

# Detects a usable HTTP proxy for WSL and records it in WSL_PROXY_URL.
# USE_LOCAL_PROXY=0 leaves HTTP(S)_PROXY untouched; the Gradle override above
# still runs because the committed gradle.properties proxy would break builds.
configure_local_proxy() {
    WSL_PROXY_URL=""
    case "${USE_LOCAL_PROXY:-auto}" in
        0|false|FALSE|no|NO)
            ;;
        1|true|TRUE|yes|YES|auto)
            local host_ip
            host_ip="$(wsl_host_ip)"
            if http_proxy_works "http://127.0.0.1:7897"; then
                WSL_PROXY_URL="http://127.0.0.1:7897"
            elif [[ -n "$host_ip" ]] && http_proxy_works "http://$host_ip:7897"; then
                WSL_PROXY_URL="http://$host_ip:7897"
            elif [[ "${USE_LOCAL_PROXY:-auto}" != "auto" ]]; then
                printf '%s\n' "No working proxy found on 127.0.0.1:7897 or ${host_ip:-<host>}:7897." >&2
            fi
            ;;
        *)
            printf 'Invalid USE_LOCAL_PROXY value: %s\n' "$USE_LOCAL_PROXY" >&2
            return 1
            ;;
    esac

    if [[ -n "$WSL_PROXY_URL" ]]; then
        export HTTP_PROXY="${HTTP_PROXY:-$WSL_PROXY_URL}"
        export HTTPS_PROXY="${HTTPS_PROXY:-$WSL_PROXY_URL}"
        printf 'WSL_PROXY=%s\n' "$WSL_PROXY_URL"
    fi

    ensure_gradle_proxy_override
}

is_java17_home() {
    local candidate="$1"
    local version_line

    [[ -x "$candidate/bin/java" ]] || return 1
    version_line="$("$candidate/bin/java" -version 2>&1 | head -n 1)"
    [[ "$version_line" =~ \"17\. ]]
}

resolve_java_home() {
    if [[ -n "${JAVA_HOME:-}" ]] && is_java17_home "$JAVA_HOME"; then
        return 0
    fi

    local resolved_java detected_java_home=""
    if resolved_java="$(command -v java 2>/dev/null)"; then
        detected_java_home="$(dirname "$(dirname "$(readlink -f "$resolved_java")")")"
    fi

    if [[ -n "$detected_java_home" ]] && is_java17_home "$detected_java_home"; then
        JAVA_HOME="$detected_java_home"
        export JAVA_HOME
        return 0
    fi

    local candidate
    for candidate in \
        /usr/lib/jvm/*17*/ \
        /opt/*jdk*17*/ \
        "$HOME"/*jdk*17*/; do
        [[ -d "$candidate" ]] || continue
        if is_java17_home "${candidate%/}"; then
            JAVA_HOME="${candidate%/}"
            export JAVA_HOME
            return 0
        fi
    done

    return 1
}

require_java17() {
    if ! resolve_java_home; then
        printf '%s\n' "JDK 17 was not found. Run: ./wsl-scripts/init-android-env.sh --install-jdk" >&2
        return 1
    fi

    local java_version
    java_version="$("$JAVA_HOME/bin/java" -version 2>&1 | head -n 1)"
    printf 'JAVA_HOME=%s\n' "$JAVA_HOME"
    printf 'JAVA_VERSION=%s\n' "$java_version"
}

find_sdkmanager() {
    local candidate
    for candidate in \
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
        "$ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager"; do
        # Shared SDK roots only contain the Windows sdkmanager.bat.
        if [[ -x "$candidate" && "$candidate" != *.bat ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done

    return 1
}

# sdk.dir in local.properties can only hold one OS-specific path. WSL scripts
# always rewrite it to ANDROID_SDK_ROOT; the Windows scripts do the same for
# E:\Android\Sdk, so builds on either side self-heal.
ensure_local_properties() {
    local local_properties="$PROJECT_ROOT/local.properties"
    local temp_file
    temp_file="$(mktemp "${TMPDIR:-/tmp}/anisubroid-local-properties.XXXXXX")"

    if [[ -f "$local_properties" ]]; then
        awk -v sdk_dir="$ANDROID_SDK_ROOT" '
            BEGIN { found = 0 }
            /^sdk\.dir=/ { print "sdk.dir=" sdk_dir; found = 1; next }
            { print }
            END { if (!found) print "sdk.dir=" sdk_dir }
        ' "$local_properties" > "$temp_file"
    else
        printf 'sdk.dir=%s\n' "$ANDROID_SDK_ROOT" > "$temp_file"
    fi

    mv "$temp_file" "$local_properties"
    printf 'ANDROID_SDK_ROOT=%s\n' "$ANDROID_SDK_ROOT"
    printf 'local.properties=%s\n' "$local_properties"
}

# What Gradle needs to build: the platform data dir, accepted licenses, and a
# build-tools dir containing Linux binaries (AGP validates aapt/aapt2 itself).
require_android_sdk() {
    local missing=false
    local build_tools_dir="$ANDROID_SDK_ROOT/build-tools/$REQUIRED_BUILD_TOOLS_VERSION"

    if [[ ! -d "$ANDROID_SDK_ROOT/platforms/android-$REQUIRED_COMPILE_SDK" ]]; then
        printf '%s\n' "Android SDK Platform $REQUIRED_COMPILE_SDK was not found at $ANDROID_SDK_ROOT." >&2
        missing=true
    fi

    if [[ ! -x "$build_tools_dir/aapt" && ! -x "$build_tools_dir/aapt2" ]]; then
        printf '%s\n' "Android SDK Build-Tools $REQUIRED_BUILD_TOOLS_VERSION has no Linux binaries at $ANDROID_SDK_ROOT." >&2
        missing=true
    fi

    if [[ ! -d "$ANDROID_SDK_ROOT/licenses" ]]; then
        printf '%s\n' "Android SDK licenses were not accepted at $ANDROID_SDK_ROOT." >&2
        missing=true
    fi

    if [[ "$missing" == true ]]; then
        if is_shared_sdk_root; then
            printf '%s\n' "Run ./wsl-scripts/init-android-env.sh to merge the missing Linux components into the shared SDK." >&2
        else
            printf '%s\n' "Run: ./wsl-scripts/init-android-env.sh --accept-licenses" >&2
        fi
        return 1
    fi
}

# Resolves the download URL of a package's Linux archive from the official
# Android SDK repository manifest.
sdk_repo_zip_url() {
    local package_path="$1"
    local repo_xml url
    repo_xml="$(curl -fsSL --retry 3 "https://dl.google.com/android/repository/repository2-1.xml")" || return 1

    url="$(printf '%s' "$repo_xml" | awk -v pkg="$package_path" '
        $0 ~ "<remotePackage path=\"" pkg "\"" { inpkg = 1 }
        inpkg && /<archive>/ { inarch = 1; buf = "" }
        inarch { buf = buf $0 "\n" }
        inarch && /<\/archive>/ {
            if (buf ~ /<host-os>linux<\/host-os>/ && match(buf, /<url>[^<]+<\/url>/)) {
                print substr(buf, RSTART + 5, RLENGTH - 11)
                exit
            }
            inarch = 0
        }
        /<\/remotePackage>/ { inpkg = 0 }
    ')"

    [[ -n "$url" ]] || return 1
    printf 'https://dl.google.com/android/repository/%s\n' "$url"
}

# Merges a Linux SDK package zip into an existing (possibly Windows-populated)
# SDK directory. Zip layouts like "android-14/" (build-tools) or
# "platform-tools/" are unwrapped so binaries land directly in $target_dir.
merge_linux_sdk_package() {
    local package_path="$1" target_dir="$2"
    local url download_dir inner

    url="$(sdk_repo_zip_url "$package_path")" || {
        printf 'Could not resolve Linux archive for %s in repository manifest.\n' "$package_path" >&2
        return 1
    }

    download_dir="$(mktemp -d "${TMPDIR:-/tmp}/anisubroid-sdk-pkg.XXXXXX")"
    printf 'Downloading %s from %s\n' "$package_path" "$url"
    curl --fail --location --retry 3 --output "$download_dir/pkg.zip" "$url"
    unzip -q "$download_dir/pkg.zip" -d "$download_dir/unpacked"

    inner="$(find "$download_dir/unpacked" -mindepth 1 -maxdepth 1 | head -n 1)"
    mkdir -p "$target_dir"
    if [[ -d "$inner" && "$(find "$download_dir/unpacked" -mindepth 1 -maxdepth 1 | wc -l)" -eq 1 ]]; then
        cp -a "$inner/." "$target_dir/"
    else
        cp -a "$download_dir/unpacked/." "$target_dir/"
    fi
    chmod -R u+x "$target_dir" 2>/dev/null || true
    rm -rf "$download_dir"
}
